# frozen_string_literal: true

require "erb"
require "digest"

module Rbag
  class Stub
    TEMPLATE = <<~RUBY
      #!/usr/bin/env ruby
      # frozen_string_literal: true

      require "fileutils"
      require "tmpdir"
      require "zlib"
      require "rubygems/package"
      require "stringio"

      module RbagStub
        def self.run(archive_bytes, app_name, entry, args)
          tmp_dir = File.join(Dir.tmpdir, "<%= dir_name %>")

          unless Dir.exist?(tmp_dir)
            # Generated by rbag <%= Rbag::VERSION %> — do not edit
            extract(archive_bytes, tmp_dir)
          end

          execute(tmp_dir, entry, args)
        end

        def self.extract(archive_bytes, dest)
          FileUtils.mkdir_p(dest)
          io = StringIO.new(archive_bytes)
          Zlib::GzipReader.wrap(io) do |gz|
            Gem::Package::TarReader.new(gz) do |tar|
              tar.each do |entry|
                dest_path = File.join(dest, entry.full_name)
                if entry.directory?
                  FileUtils.mkdir_p(dest_path)
                elsif entry.file?
                  FileUtils.mkdir_p(File.dirname(dest_path))
                  File.binwrite(dest_path, entry.read)
                  File.chmod(entry.header.mode, dest_path)
                end
              end
            end
          end
        rescue StandardError => e
          abort "rbag: extraction failed: \#{e.message}"
        end

        def self.execute(tmp_dir, entry, args)
          # Setup environment
          ENV["BUNDLE_GEMFILE"] = File.join(tmp_dir, "Gemfile")

          # Setup LOAD_PATH for standalone gems
          lib_dirs = Dir.glob(File.join(tmp_dir, "vendor/bundle/ruby/*/gems/*/lib"))
          $LOAD_PATH.unshift(*lib_dirs)
          $LOAD_PATH.unshift(File.join(tmp_dir, "lib"))

          # Run the entry point
          ARGV.replace(args)

          # Try various locations for the entry point
          possible_paths = [
            File.join(tmp_dir, entry),
            File.join(tmp_dir, "\#{entry}.rb"),
            File.join(tmp_dir, "bin", entry),
            File.join(tmp_dir, "bin", "\#{entry}.rb"),
            File.join(tmp_dir, "bin/stubs", entry)
          ]

          entry_path = possible_paths.find { |p| File.exist?(p) }

          if entry_path
            load entry_path
          else
            abort "rbag: entry point not found: \#{entry}"
          end
        end
      end

      archive_bytes = <%= archive_bytes.inspect %>
      RbagStub.run(archive_bytes, <%= app_name.inspect %>, <%= entry.inspect %>, ARGV)
    RUBY

    def self.render(archive_bytes:, app_name:, entry:)
      checksum = Digest::SHA256.hexdigest(archive_bytes)[0..11]
      dir_name = "rbag-#{app_name}-#{checksum}"

      ERB.new(TEMPLATE).result_with_hash(
        archive_bytes: archive_bytes,
        app_name: app_name,
        entry: entry,
        dir_name: dir_name
      )
    end
  end
end
