# frozen_string_literal: true

require "base64"
require "digest"

module Rex
  class Stub
    def self.render(archive_bytes:, app_name:, entry:)
      new(archive_bytes, app_name, entry).render
    end

    def initialize(archive_bytes, app_name, entry)
      @archive_bytes = archive_bytes
      @app_name      = app_name
      @entry         = entry
    end

    def render
      checksum = Digest::SHA256.hexdigest(@archive_bytes)[0, 16]
      encoded  = Base64.encode64(@archive_bytes)
      dir_name = "rex-#{@app_name}-#{checksum}"

      <<~RUBY
        #!/usr/bin/env ruby
        # frozen_string_literal: true
        # Generated by rex #{Rex::VERSION} — do not edit
        require "base64"
        require "zlib"
        require "rubygems/package"
        require "fileutils"
        require "stringio"
        require "rbconfig"
        require "tmpdir"

        BLOB = <<~'BASE64'
        #{encoded.chomp}
        BASE64

        TMP_DIR    = File.join(Dir.tmpdir, #{dir_name.inspect})
        ENTRY_PATH = File.join(TMP_DIR, "bin", #{@entry.inspect})

        unless File.exist?(ENTRY_PATH)
          begin
            FileUtils.mkdir_p(TMP_DIR)
            deferred_symlinks = []
            Zlib::GzipReader.wrap(StringIO.new(Base64.decode64(BLOB))) do |gz|
              Gem::Package::TarReader.new(gz) do |tar|
                tar.each do |entry|
                  dest = File.join(TMP_DIR, entry.header.name)
                  case entry.header.typeflag
                  when "5"
                    FileUtils.mkdir_p(dest)
                    File.chmod(entry.header.mode, dest)
                  when "2"
                    FileUtils.mkdir_p(File.dirname(dest))
                    unless File.symlink?(dest) || File.exist?(dest)
                      begin
                        File.symlink(entry.header.linkname, dest)
                      rescue NotImplementedError, Errno::EPERM
                        deferred_symlinks << [entry.header.linkname, dest]
                      end
                    end
                  else
                    FileUtils.mkdir_p(File.dirname(dest))
                    File.binwrite(dest, entry.read)
                    File.chmod(entry.header.mode, dest)
                  end
                end
              end
            end
            deferred_symlinks.each do |linkname, dest|
              next if File.exist?(dest)
              target = File.expand_path(linkname, File.dirname(dest))
              FileUtils.cp(target, dest) if File.exist?(target)
            end
          rescue => e
            FileUtils.rm_rf(TMP_DIR)
            abort "rex: extraction failed: \#{e.message}"
          end
        end

        exec(RbConfig.ruby, ENTRY_PATH, *ARGV)
      RUBY
    end
  end
end
